spring:
  profiles: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: 5000

# Enable CORS for all endpoints
cors:
  allowed-origins: 
    - http://hotel-management-ui.s3-website.ap-south-1.amazonaws.com
    - https://hotel-management-ui.s3-website.ap-south-1.amazonaws.com
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true
