spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

server:
  port: 5000

# Enable CORS for all endpoints
cors:
  allowed-origins: 
    - http://hotel-management-ui.s3-website.ap-south-1.amazonaws.com
    - http://52.66.135.123:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "Origin, Content-Type, Accept, Authorization, X-Requested-With"
  exposed-headers: "Authorization"
  allow-credentials: true
  max-age: 3600
